src/app/components/elements/UserKeys.scss
src/app/components/elements/WalletSubMenu.jsx
src/app/components/pages/UserProfile.jsx
src/app/components/pages/WalletIndex.jsx
src/app/utils/ExtractMeta.js
src/server/app_render.jsx
src/server/index.js
src/shared/UniversalRender.jsx

- do not show disabled cursor on private key hover
- use Steemit Wallet title for meta tags
- rename Password tab to Change Password
- re-add Blog tab to user wallet menu
- fix back button infinite loop

ux improvements

---

src/app/redux/UserSaga.js

This allows the user to use an active key to generate the image upload. The error message should probably be 'Login with active key' here because the next step of actually updating requires an active key either way until at least after the next hard fork (and the user will still be prompted for their active key when pressing 'update'), but it still allows the upload to succeed with either a posting or an active key.
The purpose is to minimize confusion, as some users were getting stuck on trying to upload a profile picture because it first required their posting key, and then later required also their active key. Requiring two keys to perform this action is bad UX.
Closes #28 
Also requires this PR to be merged and deployed for imagehoster: https://github.com/steemit/imagehoster/pull/104

Allow active key for image upload from settings page in wallet

---

src/app/components/modules/Header/index.jsx
src/app/components/modules/LoginForm.jsx
src/app/components/pages/Login.jsx
src/app/components/pages/Witnesses.jsx

- fixes #24: redirect to wallet when logging in via login.html
- fixes #25: use basic login type from login.html
- fixes #30: redirect to home when logging out
bonus:
- fix #23: all witness links are external. fix broken links to steemit.com

login and minor fixes

---

.circleci/config.yml
Makefile
README.md

Right now there is no feedback for tests in CodeBuild. This will allow PRs to see test status by running in a publicly accessible Circle CI run.

Update Circle CI Config

---

src/app/help/en/faq.md
src/app/help/en/welcome.md

Community - Updated FAQ and Welcome page for HF21

---

package.json
yarn.lock

update sequelize to 5.3.0

---

src/app/components/modules/UserWallet.jsx

This issue came up when testing #119 bug. May not be the root cause but it creates major issues rendering wallet page in some cases.

fail gracefully when gprops not loaded

---

src/server/api/account_recovery.js
src/server/api/general.js
src/server/sign_up_pages/enter_confirm_email.jsx

fix sql order params

---

src/app/redux/TransactionReducer.js

From @quochuy #125:
> ![Screen Shot 2020-01-15 at 6 16 42 pm](https://user-images.githubusercontent.com/310654/72413369-c7e44e00-37c3-11ea-81c4-9b0fdfac9e25.jpg)

Community - Friendly error message for transfer to an unknown user

---

src/server/api/account_recovery.js
src/server/api/general.js
src/server/sign_up_pages/enter_confirm_email.jsx

Refs #118 
And copy of PR:
https://github.com/steemit/wallet/pull/121/commits/81deaa4c36520bbb272a7c270091bf8fddec7bd6

118 recovery bug take 2

---

src/app/components/elements/ConfirmDelegationTransfer/index.jsx
src/app/components/elements/ConfirmTransfer/index.jsx
src/app/components/modules/Transfer.jsx
src/app/components/modules/UserWallet.jsx
src/app/locales/en.json

Add delegation modal

---

src/app/utils/NormalizeProfile.js

https://github.com/steemit/steem/issues/3274
https://github.com/steemit/condenser/issues/3744

fix cover image not updating

---

.gitignore
src/db/migrations/20200805144408-create-tron-user.js
src/db/migrations/20200805144503-create-tron-reward.js
src/db/migrations/20200805144517-create-tron-reward-history.js
src/db/models/tron_reward.js
src/db/models/tron_reward_history.js
src/db/models/tron_user.js

DB structure migration files and db models.

Tron reward db structure

---

src/db/migrations/20200805144408-create-tron-user.js

tran_addr_active_time => tron_addr_active_time

fix wrong table field

---

src/server/server.js

Set environment `TRON_REWARD_SWITCH=on` will enable reward backend api.

add tron reward backend api switch

---

src/app/components/modules/TronCreateOne.jsx
src/app/components/modules/UserWallet.jsx
src/app/redux/UserReducer.js
src/app/redux/UserSaga.js
src/app/utils/ServerApiClient.js
src/db/cache/index.js
src/db/models/tron_user.js
src/db/utils/user_utils.js
src/server/api/tron_reward.js

1. add cache clear api
2. fix redis cache update bug
3. fix the pending trx reward couldnot claim
4. add new way to claim pending trx reward
5. add more console error info during binding tron address
6. fix trx display precision

Claim reward bug

---

src/app/locales/en.json
src/app/locales/zh.json

change the "update tron address" button's text.

change text

---

src/app/locales/ko.json

It's a strange phrase with the words cut in the middle.

Corrected incorrect sentences.

---

src/app/components/pages/NotFound.jsx
src/shared/UniversalRender.jsx

Fix `invariant violation: could not find store'' in the context of connect(app)` error when server render.

fix not found page serverRender

---

src/db/cache/index.js
src/db/migrations/20230203042505-add_tron_reward_updated_at_index.js
src/db/models/tron_reward.js
src/db/utils/user_utils.js
src/server/api/tron_reward.js

* Change calculation of pending_claim_reward method
* Change binding tron address method
* Remove the reward_type filed in future.

Tron reward logic fix
